apiVersion: apps/v1
kind: Deployment
metadata:
  name: ovysotskyi-site-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ovysotskyi-site
  template:
    metadata:
      labels:
        app: ovysotskyi-site
    spec:
      containers:
      - name: ovysotskyi-site
        image: visotskiyw4o/ovysotskyi-site-hub:latest
        ports:
        - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: ovysotskyi-site-service
spec:
  selector:
    app: ovysotskyi-site
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: NodePort

